### ISSUE TITLE
WAS에 따라서 파일을 못가져 오는 오류가 있습니다.

### ISSUE THREAD

**Issue by hyunjun19** [hyunjun19/axu4j#37]
JBOSS wildfly 같은 경우 war파일을 풀지 않고 그냥 돌기 때문에 파일의 경로가 `../ROOT.war/modal.jsp` 이렇게 처리되어 파일을 못찾는 경우가 발생하고 있습니다.

해당 문제는 `getResource`메서드에서 `getResourceAsStream` 메서드로 변경하면 해결될것 같습니다.

패치에는 3~4일 정도 예상됩니다.

**Comment by hyunjun19** [comment]
해당 문제는 WAS가 war 파일을 풀지 않고 그냥 deploy하기 때문인것 같습니다.

http://stackoverflow.com/questions/14368629/is-it-possible-to-deploy-an-exploded-war-file-unzipped-war-in-jboss-as-7

이 링크를 참조해서 war를 풀어서 deply 해보시기 바랍니다.

혹시 테스트 해보신 분이 계시면 피드백 부탁드립니다.

**Comment by hjlee83** [comment]
안녕하세요
지금 jdk 1.5 개발환경, 실행환경에서 작업을 하려고 합니다.

java.lang.UnsupportedClassVersionError: Bad version number in .class file (unable to load class com.github.mustachejava.MustacheFactory)

이런 에러가 나와서 확인해보니
axu4j 의 pom.xml은 1.5이지만

com.github.spullara.mustache.java 의 기본 셋팅은 1.6 이상입니다.

<dependency>
			<groupId>com.github.spullara.mustache.java</groupId>
			<artifactId>compiler</artifactId>
			<version>0.8.17</version>
		</dependency>

이 부분이

<dependency>
		    <groupId>com.github.spullara.mustache.java</groupId>
		    <artifactId>compiler-jdk5</artifactId>
		    <version>0.8.10</version>
		</dependency>

이렇게 바껴야 구동이 되네요.
