### ISSUE TITLE
JDK 1.5 구동문제

### ISSUE THREAD

**Issue by hjlee83** [hyunjun19/axu4j#39]
안녕하세요 
운이 나쁘게도 JDK5 개발환경 및 실행환경에서
개발을 하게된 개발자입니다.

axu 를 사용하려다 보니
axu4j 라는게 있어서 사용을 하려고 합니다.

일단 감사합니다.

현재 jdk 1.5에서는 제대로 동작 안하는 부분이 있습니다.

에러 메시지는 
java.lang.UnsupportedClassVersionError: Bad version number in .class file (unable to load class com.github.mustachejava.MustacheFactory)
입니다.

axu4j 는 jdk5 로 컴파일 되어있지만
com.github.spullara.mustache.java compiler는 안타깝게도 jdk 6 이상을 지원합니다.

사용하기 위해서는
com.github.spullara.mustache.java compiler-jdk5를 사용해야합니다.

현재 궁여지책으로

		<dependency>
		    <groupId>com.github.spullara.mustache.java</groupId>
		    <artifactId>compiler-jdk5</artifactId>
		    <version>0.8.10</version>
		</dependency>

                 <dependency>
			<groupId>com.axisj</groupId>
			<artifactId>axu4j</artifactId>
			<exclusions>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
			    	<artifactId>logback-classic</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.github.spullara.mustache.java</groupId>
			    	<artifactId>compiler</artifactId>
				</exclusion>
			</exclusions>
			<version>1.0.0-RELEASE</version>
		</dependency>
이렇게 사용중입니다.
로그 역시 전자정부프레임워크랑 충돌이 나서 제외시켰습니다.

readme에 별도 표기가 되어있지 않아서
나중에 ReadMe에 방법을 제안하시거나
패치때 적용되게 변경해놓으셔야할것 같습니다.

감사합니다.

**Comment by hyunjun19** [comment]
피드백 감사합니다.
바로 README에 별도 표기 하겠습니다.
